# Site settings
title: "Onditi, KO | Kenneth Otieno Onditi | Kenneth Onditi" 
# description: "A brief description of your website."
url: "https://kennott.github.io"
baseurl: ""

# Author information
author: "Kenneth Otieno Onditi"
  name: "Onditi, KO."
  email: "okennott@gmail.com"

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Navigation settings (Optional)
nav:
  - Home: /index.html
  - About: /about.html
  - Blog: /blog.html

# Social media links (Optional)
social_links:
  scholar: "https://scholar.google.com/citations?user=qnHYvIIAAAAJ&hl=en"
  github: "https://github.com/okennott"
  twitter: "https://x.com/kennott"


# Permalinks settings (Optional)
permalink: /:year/:month/:day/:title/

# Markdown settings (Optional)
markdown: kramdown
